### ISSUE TITLE
Access to Google Drive

### ISSUE THREAD

**Issue by muriloime** [ml4ai/automates#172] opened 2021-01-18 18:13 UTC
Hello there, first of all, congratulations on the project, I found it very interesting ! 

However I could not test/reproduce it because it requires access to GDrive files such as  "ASKE-AutoMATES/Data/equation_decoding/arxiv2018-downsample-aug-model_step_80000.pt". Could you please add the Gdrive path to the documentation? 

Many thanks 
Murilo

**Comment by adarshp** [comment] 2021-01-18 18:28
@muriloime Thanks for your interest! Could you please describe the steps you took so we can try to reproduce the error?

**Comment by muriloime** [comment] 2021-01-19 10:32
Of course, @adarshp . I am trying to reproduce the steps for eqdec installation at the moment as per

https://github.com/ml4ai/automates/blob/0657cf44caf82267be07c68de4acad08f6e722e6/automates/equation_reading/equation_translation/eqdec/readme.txt

**Comment by adarshp** [comment] 2021-01-19 16:04
Thans @muriloime  - the model in question is a pytorch model that was trained by us on a large arXiv dataset. The Google Drive folder in question is only accessible to internal team members.

@cl4yton - is the model (`arxiv2018-downsample-aug-model_step_80000.pt`) something we can make publicly available? If so, I can put it up on vanga and update the eqdec README with its location.

**Comment by muriloime** [comment] 2021-01-19 17:17
Thank you @adarshp , I am very familiar with torch models. Since the repo is licensed under Apache I was wondering if you could make public the trained model (and the other relevant files, probably too), as this research is very close in scope ( but not application) to my own currently

Many thanks

**Comment by cl4yton** [comment] 2021-01-20 00:20
Hi @muriloime : Thank you for your interest, and apologies that you haven't been able to access the model. Can you please try accessing the model using this link?:
https://drive.google.com/file/d/1cMFn4e4T9N4KJRE5LO3WBq23Afjy3--f/view?usp=sharing
This should be world read-accessible. If that doesn't work, we'll try the route @adarshp suggested (placing it on one of our servers).

**Comment by muriloime** [comment] 2021-01-20 21:46
Lovely, thank you very much @cl4yton . I am having some problems with the docker eqdec build, as the master branch for OpenNMT dropped support for images (they only allow text translation ATM for the version 2.0), in such a manner that if one tries to build the docker image, it breaks. 

If you accept PRs I can modify the docker to include the correct version of the package  ( `pip install https://github.com/OpenNMT/OpenNMT-py/archive/legacy.zip` , but in this case the app.py needs to use the command `onmt_translate`)

Also, if you think it is ok, I can also make the docker image available in dockerhub. 

cheers

**Comment by cl4yton** [comment] 2021-01-24 01:14
Hi @muriloime , Yes, we accept PRs. Please open a PR and we'll review. Thanks!

**Comment by pauldhein** [comment] 2021-07-06 15:19
Closing this issue since this conversation seems to be concluded.

**Closed by pauldhein** 2021-07-06 15:19 UTC
